export const PATHS = {
    HOME: '/',
    SIGNIN: '/signin',
    SIGNUP: '/signup',
    FORGOT_PASSWORD: '/forgot-password',
    CREATE_NEW_PASSWORD: '/create-new-password',
    OTP_VERIFICATION: '/otp',
    POSTS: '/posts',
    PROFILE: '/profile',
    WALLET: '/wallet',
    NOTIFICATION: '/notification',
    REWARDS: '/rewards',
    FEEDBACKS: '/feedbacks',
    ADMIN_FEEDBACKS: '/admin/feedbacks',
    USER_PROFILE: '/user-profile/:id',
};
