export type ReportAccountReasons =
    | 'SPAMMING'
    | 'HARASSMENT'
    | 'INAPPROPRIATE_LANGUAGE'
    | 'FAKE_ACCOUNT'
    | 'IMPERSONATION'
    | 'OFFENSIVE_CONTENT'
    | 'SELF_PROMOTION'
    | 'SCAM_ATTEMPT'
    | 'COPYRIGHT_VIOLATION'
    | 'PRIVACY_VIOLATION'
    | 'MALICIOUS_LINKS'
    | 'FALSE_INFORMATION'
    | 'UNAUTHORIZED_ADVERTISING'
    | 'HATE_SPEECH'
    | 'ILLEGAL_ACTIVITIES';

export const reportAccountReasons: ReportAccountReasons[] = [
    'SPAMMING',
    'HARASSMENT',
    'INAPPROPRIATE_LANGUAGE',
    'FAKE_ACCOUNT',
    'IMPERSONATION',
    'OFFENSIVE_CONTENT',
    'SELF_PROMOTION',
    'SCAM_ATTEMPT',
    'COPYRIGHT_VIOLATION',
    'PRIVACY_VIOLATION',
    'MALICIOUS_LINKS',
    'FALSE_INFORMATION',
    'UNAUTHORIZED_ADVERTISING',
    'HATE_SPEECH',
    'ILLEGAL_ACTIVITIES',
]
